### ISSUE TITLE
Integração via API

### ISSUE THREAD

**Issue by giovannibonetti** [servicosgovbr/manual-script-chatbot-login-unico#1]
Boa tarde,
sou desenvolvedor e aqui na empresa nós gostaríamos muito de integrar nosso sistema com o login do governo.

O nosso objetivo é uma integração com o portal do MeuINSS para que o cidadão possa carregar seus dados previdenciários diretamente de lá. Hoje em dia nós usamos o PDF gerado pelo portal com as contribuições previdenciárias, mas o PDF não é um formato muito bom para isso, precisamos fazer uma série de etapas para que o software consiga lê-lo, então ajudaria um monte se a gente conseguisse fazer uma chamada para alguma API do governo que retornasse um JSON das informações que precisamos.

De qualquer forma, o nosso desafio atual é a parte de autenticação. Existe alguma API de autenticação para que o cidadão possa logar por meio de um site de terceiros? O ideal seria algo do tipo OAuth, mas qualquer coisa ajuda.

Grato.

**Comment by caduvieira** [comment]
Esse projeto não trata disso. O projeto para o login único é o https://github.com/servicosgovbr/manual-roteiro-integracao-login-unico 

Mas o que você deseja é uma API e esse tipo de API é tratado no https://conecta.gov.br
