### ISSUE TITLE
Autenticação dois fatores

### ISSUE THREAD

**Issue by matheusmacedoap** [servicosgovbr/manual-script-chatbot-login-unico#27]
Após realizar restauração do celular, me deparei com a seguinte situação:

Como obter acesso a conta com autenticação dois fatores ativada que só envia o codigo por meio do aplicativo que não esta mais instalado no celular.

Sugestão envio por SMS.

**Comment by claudiohenrique-dev** [comment]
Eu consegui através da redefinição de senha pelo método de reconhecimento facial

**Comment by matheusmacedoap** [comment]
> Eu consegui através da redefinição de senha pelo método de reconhecimento facial

Depois eu conseguir dessa forma mesmo, porém nao tinha nada explicativo para fazer dessa forma e eu fiquei meio perdido, mas deu certo obrigado.
