### ISSUE TITLE
Problemas ao visualizar os contratos CLT

### ISSUE THREAD

**Issue by JonsCodi** [servicosgovbr/manual-script-chatbot-login-unico#33]
Pessoal, bom dia.

Não sei se é nesse repositório que crio uma Issue mas eu não sei onde eu consigo reportar esse problema. 

Deem uma olhada no print: 
![clt](https://user-images.githubusercontent.com/24721120/151799053-81473b0c-be25-4842-b0ec-154c627354e6.png)

Estou ja tendo esse problemas faz semanas, entao achei melhor abrir essa issue pra reportar.

Obrigado.

**Comment by caduvieira** [comment]
Esse repositório é sobre o manual do Login GOVBR. O LoginGOVBR é só uma forma de autenticar as pessoas para usarem serviços públicos digitais. Pela sua mensagem é o serviço específico de CLT.

Pelo site https://www.gov.br/pt-br/servicos/obter-a-carteira-de-trabalho (Item Outras informações) o telefone de contato é o 158. 

E sugiro ver o site https://www.gov.br/pt-br/temas/carteira-de-trabalho-digital e, na FAQ, tem o link para um formulário de contato no item 3 da FAQ e ler a FAQ para ver se outro item te ajuda. Infelizmente não tenho, e nem ninguém do projeto Login GOVBR, tem informações específicas de contato dos vários serviços públicos digitais que utilizam o Login.
