### ISSUE TITLE
Solução para o código ERL0002200

### ISSUE THREAD

**Issue by asm95** [servicosgovbr/manual-script-chatbot-login-unico#4]
Ao realizar a tentativa de login, o sistema do INSS solicita ao usuário consultar a página de perguntas frequentes (FAQ), a qual não possui referência para o erro com o código `ERL0002200`.

<img src="https://user-images.githubusercontent.com/13230288/108536941-c9801f80-72bb-11eb-9145-c050c69f5d3d.png" width="200">

**Comment by GabrielMioranza** [comment]
Acontece o mesmo aqui

**Comment by asm95** [comment]
@GabrielMioranza pelo que eu me informei até agora, o bloqueio da conta pode se dar pela detecção de uma possível fraude[1]. Um exemplo é a tentativa de realização do login com uma senha incorreta diversas vezes. Porém esse caso é bastante comum de ocorrer e não há um guia de como proceder nesse caso.

[1] Segundo fontes do Dataprev, estão ocorrendo diversas tentativas de fraudes no sistema, por isso o filtro mais agressivo.

**Comment by carloshenriquefbf** [comment]
Alguém conseguiu resolver esse problema? Ou pelo menos conseguiu acessar depois de ter sido bloqueado? Se conseguiu, teve que esperar quanto tempo?

**Comment by GabrielMioranza** [comment]
Não consegui mais acessar e nem mesmo resetar novamente a senha.

**Comment by GabrielMioranza** [comment]
E aparentemente ninguém olha as issues

**Comment by caduvieira** [comment]
Vocês querem adicionar uma pergunta/resposta na FAQ? Para problemas com a conta pela FAQ é melhor entrar em contato pelo http://faq-login-unico.servicos.gov.br/en/latest/_perguntasdafaq/comopossoteajudar.html

**Comment by asm95** [comment]
Boa tarde @caduvieira, queremos uma _resposta_ de vocês sobre o erro `ERL0002200` no FAQ. O código não nos informa nada do que aconteceu e como o cidadão deve proceder nesse caso. Vocês são os desenvolvedores e _sabem_ o que isso significa. Precisamos da documentação disponível para o público[1], no site. Desde já agradeço.

[1] Por exemplo: abra uma página no FAQ sobre "bloqueio de usuário" e como resolver. Assim diminuindo a demanda da população sobre as agências, o 135 e outros portais como o Reclame Aqui.

**Comment by caduvieira** [comment]
Não sou o desenvolvedor. @higogomes pode ver isso?

**Comment by paulo-matos** [comment]
Mesmo problema aqui, ansioso pela solução ou informações sobre o erro.

**Comment by JonsCodi** [comment]
Há algum tipo de contato telefônico para resolver isso? Já estou há uns meses trocando email com o robozinho idiota deles para entenderem de que EU sou EU mesmo com as selfies segurando o meu documento mas sem sucesso, os robôs não conseguem entender a foto e fica em loop. 

Ajudaria se vocês tivessem um contato FAQ HUMANO e nao robotizado que não resolve porra nenhuma.

**Comment by caduvieira** [comment]
@higogomes pode verificar por favor?

**Comment by higogomes** [comment]
Prezado Jonas,

Favor encaminhar o problema para email despd@economia.gov.br.

Descreva a situação e adicione fotos para ajudar no relato.

Em seg, 8 de mar de 2021 14:16, caduvieira <notifications@github.com>
escreveu:

**Comment by JonsCodi** [comment]
Enviei!

**Comment by higogomes** [comment]
Ótimo,

Favor aguardar.


Em seg, 8 de mar de 2021 14:56, Jonas Gomes <notifications@github.com>
escreveu:

**Comment by JonsCodi** [comment]
Muito obrigado, problema resolvido.

**Comment by CiroboyBR** [comment]
O problema ocorre quando alguem erra a senha diversas vezes. O sistema desbloqueia automaticamente depois de 4~6h.

**Comment by HudsondeSouzaSantos** [comment]
Encontrei essa solução no próprio site meu gov:

https://www.gov.br/governodigital/pt-br/conta-gov-br/perguntas-frequentes/.

Se por algum motivo você não tiver mais acesso ao aplicativo gov.br no seu celular, você ainda pode desabilitar a verificação em duas etapas fazendo a recuperação de senha.

Na tela de [login](https://acesso.gov.br/), digite seu CPF e, na tela seguinte, clique em "Esqueci minha senha" para recuperar sua senha por meio do Reconhecimento facial ou pelo login com algum dos bancos credenciados.

Ao recuperar sua senha, a verificação em duas etapas será automaticamente desabilitada. Você pode habilitá-la novamente a qualquer momento.

**Comment by Pedrolustosa** [comment]
Minha opção: Obter Confiabilidade por Validação Facial (TSE)
Pessoal, estou tentando Gerar QR Code para poder fazer o meu Reconhecimento Facil. Mas, está apresentando o seguinte erro:  Erro de comunicação com serviço de dados biométricos para adquirir confiabilidade comprovada (ERL0012100). Já faz 2 dias e não consigo por conta desse erro.

**Comment by Gustavogh20** [comment]
![Opera Instantâneo_2022-03-12_142536_cadastro acesso gov br](https://user-images.githubusercontent.com/101472393/158028206-124f75b3-fbad-42b0-91e8-1db855a4f839.png)


Erro (ERL0002200) na criação de uma conta. Se alguém souber a solução eu fico grato!

**Comment by xstaticprocess** [comment]
> Isso pode ser problemas no serviço de API do TSE.
> 
> > Minha opção: Obter Confiabilidade por Validação Facial (TSE) Pessoal, estou tentando Gerar QR Code para poder fazer o meu Reconhecimento Facil. Mas, está apresentando o seguinte erro: Erro de comunicação com serviço de dados biométricos para adquirir confiabilidade comprovada (ERL0012100). Já faz 2 dias e não consigo por conta desse erro.
> > Reconhecimento facial não realizado Biometria facial não encontrada. Não foi possível validar sua foto em nossas bases

E como se resolve isso? No meu caso a biometria foi coletada em 2017, no site do TSE consta como regular e biometria coletada, no e-titulo minha biometria está la, com foto e confirmação, mas ao tentar gerar o QR code recebo a mensagem: "Não identificamos cadastro de sua biometria. (ERL0012200)"
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/57876399/161105055-771949e8-d1b2-4070-9b37-4cff0110d569.png">
<img width="881" alt="image" src="https://user-images.githubusercontent.com/57876399/161105213-cce799b5-21d7-4f58-bed3-797af3430cde.png">

**Comment by gustavosrodrigues** [comment]
> > Isso pode ser problemas no serviço de API do TSE.
> > > Minha opção: Obter Confiabilidade por Validação Facial (TSE) Pessoal, estou tentando Gerar QR Code para poder fazer o meu Reconhecimento Facil. Mas, está apresentando o seguinte erro: Erro de comunicação com serviço de dados biométricos para adquirir confiabilidade comprovada (ERL0012100). Já faz 2 dias e não consigo por conta desse erro.
> > > Reconhecimento facial não realizado Biometria facial não encontrada. Não foi possível validar sua foto em nossas bases
> 
> E como se resolve isso? No meu caso a biometria foi coletada em 2017, no site do TSE consta como regular e biometria coletada, no e-titulo minha biometria está la, com foto e confirmação, mas ao tentar gerar o QR code recebo a mensagem: "Não identificamos cadastro de sua biometria. (ERL0012200)" <img alt="image" width="1167" src="https://user-images.githubusercontent.com/57876399/161105055-771949e8-d1b2-4070-9b37-4cff0110d569.png"> <img alt="image" width="881" src="https://user-images.githubusercontent.com/57876399/161105213-cce799b5-21d7-4f58-bed3-797af3430cde.png">

Eu também estou com o mesmo problema e tenho a biometria coletada.

**Comment by gabawan** [comment]
Estou com o mesmo problema! Biometria cadastrada no TRE mas o gov não reconhece, portanto não consigo aumentar o selo. Liguei para o TRE, Banco Central, Bancos que fazem a portabilidade... ninguém me ajudou. Preciso aumentar o nível da conta com urgência. Francamente acho um desrespeito essa situação, estou desde novembro de 2022 tentando resolver.

**Comment by caduvieira** [comment]
Não vejo como os bancos possam te ajudar como reconhecimento biométrico do TSE. Se eu fosse você iria no TSE sem comentar sobre o aplicativo e pediria para refazer o reconhecimento biométrico por causa de não ser reconhecido corretamente. O aplicativo de login não armazenam dados biometricos. Se está fazendo todo o procedimento certo e não está sendo reconhecido há chance de que os dados biométricos coletados não estão ok.

**Comment by caduvieira** [comment]
Tente os procedimentos descritos em:

https://www.gov.br/conecta/catalogo/apis/validacao-biometrica
'APIs são a base para a troca automática e segura de informações entre os sistemas e não estão disponíveis para acesso pelo cidadão. 

Caso esteja com dificuldade em acessar sua conta gov.br, tente recuperá-la seguindo os passos nesta [página](http://faq-login-unico.servicos.gov.br/en/latest/_perguntasdafaq/formarrecuperarconta.html) ou abra uma solicitação no [Atendimento ao usuário – Conta GOV.BR](https://portaldeservicos.economia.gov.br/atendimento/).   

Caso a dificuldade seja no reconhecimento facial do aplicativo gov.br, reinstale o aplicativo gov.br no celular e tente realizar o procedimento novamente. 

Para demais problemas, envie um e-mail para [atendimentogovbr@economia.gov.br](mailto:atendimentogovbr@economia.gov.br) e você receberá instruções gerais sobre como solucionar problemas mais comuns. Fique atento à caixa de spam ou "lixo eletrônico"."

**Comment by caduvieira** [comment]
A API da biometria facial não lista os possíveis erros https://www.gov.br/conecta/catalogo/apis/validacao-biometrica/swagger.json/swagger_view#tag/API-Biometria-Facial.  

Parece, sem ter acesso a mais informações, que, nesse caso de "Não identificamos o cadastro de sua biometria", ou o CPF não foi enviado corretamente pelo aplicativo ou seu CPF, no TSE, não consta como biometria em algum banco de dados do TSE.

**Comment by gabawan** [comment]
Entrei em contato com bancos pois também tentei aumentar meu selo através do Internet banking, mas voltando à biometria, meus dados estão devidamente registrados no TSE. Não há motivos para não me deixarem aumentar o selo de confiabilidade. Sem esse selo eu não consigo gerar notas e portanto receber meu salário.  Isso é absurdo! 
![IMG-20230413-WA0003](https://user-images.githubusercontent.com/130020183/231780569-aea72c92-24c6-4138-b61e-ef591d688150.jpg)

**Comment by AilmaPereira** [comment]
Também estava com exatamente o mesmo problema de todos. No aplicativo do e-Titulo constava como que minha biometria estava coletada e processada com sucesso, mas o site do Gov.br dizia que não constava a biometria no TSE.

Caçando no app do e-titulo, consegui encontrar um processo de validação da foto que dependia da biometria.
Fiz o processo e apareceu o status abaixo. Aparentemente deu erro na coleta da minha biometria.

O engraçado é que antes das ultimas eleições estava tudo certo com a minha foto. Mas agora ela não aparece mais, possível que na ultima eleição a coleta nao foi satisfatoria e eles removeram minha foto. Sem biometria no TSE, sem foto. E sem foto no TSE o Gov.br não consegue validar o rosto.

![image](https://github.com/servicosgovbr/manual-script-chatbot-login-unico/assets/133249669/d0e35d1e-03a4-4414-821e-fa4520df3900)

Se alguém quiser tentar o mesmo processo, é só ir nessa opção quase no fim da lista de opções do app do e-Título.
Apesar de o status estar com ok na biometria, fiz o processo aqui e o erro apareceu.

![image](https://github.com/servicosgovbr/manual-script-chatbot-login-unico/assets/133249669/046fd8a1-fa64-400d-b823-ff8907c50896)

**Comment by Paul23player** [comment]
estava tendo 2 problemas para resolver meu login: 1 o carregamento facil não funciona pelo navegador, tem que baixar o app e fazer por la. 2 o carregamento facial falha com oculos, bone eou má iluminação. depois consegui trocar a senha e deu tudo certo, tudo isso pra eu poder acesar a porc@ri@ da CNH digital.

**Comment by isomartecnologo** [comment]
> estou precisando fazer uma procuração para o imposto de renda, mas meu pai faleceu ano passado. O site do gov da erro quando tento entrar na conta com cpf dele. Alguem saberia como ajudar? Erro: "Encontramos uma divergência no seu cadastro e não será possível realizar o login. Caso essa divergência já tenha sido resolvida junto à RFB, tente novamente em alguns instantes. (ERL0001200)"

Você não conseguirá mais acessar a conta dele no GOV.BR, pois agora as certidões de óbitos são geradas e cadastradas diretamente no sistema do governo. O cartório é que faz isso. Se vc realizar uma consulta de CPF no site da Fazenda, verá que consta o óbito. Com isso, pela ideia deles, um morto não pode movimentar sua conta GOV por questões de segurança.
