### ISSUE TITLE
Serviço de recuperação de conta não está funcionando

### ISSUE THREAD

**Issue by Daniel-Arayala** [servicosgovbr/manual-script-chatbot-login-unico#42]
Eu entrei minha senha corretamente (salva no navegador) três vezes e tive minha conta bloqueada. Após digitar meu CPF no campo abaixo:

![image](https://user-images.githubusercontent.com/47539834/197814724-df2c98ae-6ff3-4b6c-8387-d9cd0857327c.png)

e clicar em continuar aparece a opção **Recuperar conta**:

![image](https://user-images.githubusercontent.com/47539834/197816286-5ccb823d-166b-4845-91fd-edf5e3faf4c2.png)

Contudo, ao clicar na opção de recuperação de conta abre uma pagina com o erro `504 Gateway Time-out`. Tentei nos browsers: **Google Chrome**, **Mozilla Firefox**, **Safari pelo celular**, **Microsoft Edge* e **Brave** em janelas anônimas e normais e o erro ainda persiste. 

![image](https://user-images.githubusercontent.com/47539834/197820934-db6b63b5-ccb4-47cc-8a12-cda153df2a26.png)

**Comment by caduvieira** [comment]
Hoje (25/10/22) está ocorrendo uma falha de conexão do serviço de login do gov.br . A previsão de retorno é para hoje no final da tarde. Irei fechar essa issue e caso persista favor reabrir a mesma.
