### ISSUE TITLE
gov.br

### ISSUE THREAD

**Issue by eltongviana** [servicosgovbr/manual-script-chatbot-login-unico#49]
O código informado é incorreto. Clique em Gerar Código de Acesso em seu aplicativo gov.br e digite abaixo o código gerado.

**Comment by caduvieira** [comment]
Sua issue não trás nenhuma informação relevante, você não colocou nada para que o pessoal possa começar a te auxiliar. Abra chamado no portal de serviços caso ainda precise de auxílio.
