### ISSUE TITLE
Status 431 - Associar Certificado Digital

### ISSUE THREAD

**Issue by fsfelipe** [servicosgovbr/manual-script-chatbot-login-unico#5]
Ao tentar associar o certificado digital a minha conta, a resposta veio com status 431 

![Screen Shot 2021-03-09 at 9 02 15 AM](https://user-images.githubusercontent.com/8129939/110469198-1b94b380-80b8-11eb-9fee-551e6e3d1ff2.png)

**Comment by igorinhu** [comment]
Estou tendo o mesmo problema @higogomes. 
Como eu já possuia uma conta govbr, não consegui associar meu certificado digital. Com isso, não estou conseguindo acessar diversos serviços que exigem perfil ouro.
